services:
  # FastAPI Backend
  backend:
    build: ./backend
    container_name: engr-excellence-backend-fastapi
    ports:
      - "${BACKEND_PORT:-8570}:8570"
    env_file:
      - .env
    environment:
      # Override specific variables for Docker environment
      - MONGODB_URL=${MONGODB_URL:-mongodb://mongo:27017}
      - HOST=0.0.0.0
      - PORT=8570
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  # Next.js Frontend
  frontend:
    build: ./frontend
    container_name: engr-excellence-frontend-nextjs
    ports:
      - "${FRONTEND_PORT:-8571}:8571"
    env_file:
      - .env
    environment:
      # Override specific variables for Docker environment
      - NODE_ENV=production
      - PORT=8571
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: engr-excellence-mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    env_file:
      - .env
    environment:
      # Override specific variables for MongoDB
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-fastapi_db}
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    restart: unless-stopped

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: engr-excellence-mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    env_file:
      - .env
    environment:
      # Override specific variables for MongoDB Express
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER:-mongo}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT:-27017}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD:-admin123}
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
