version: "3.8"

services:
  # Development API container
  dev-api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: engr_excellence_dev
    volumes:
      # Mount the entire workspace
      - ..:/workspace:cached
      # Mount git config and SSH keys
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
      - ~/.ssh:/home/vscode/.ssh:ro
      # Persist shell history
      - dev_shell_history:/home/vscode/.history
      # Persist VS Code extensions
      - dev_vscode_extensions:/home/vscode/.vscode-server/extensions
      # Persist pip cache
      - dev_pip_cache:/home/vscode/.cache/pip
    environment:
      - PYTHONPATH=/workspace/backend
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=fastapi_db_dev
      - DEBUG=True
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8570:8570" # FastAPI
      - "5678:5678" # Python debugger
    depends_on:
      - mongo
      - redis
    networks:
      - dev-network
    # Keep container running
    command: sleep infinity
    # Enable init for proper signal handling
    init: true

  # MongoDB for development
  mongo:
    image: mongo:7.0
    container_name: engr_excellence_mongo_dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=fastapi_db_dev
    volumes:
      - dev_mongodb_data:/data/db
      - ../backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - dev-network
    restart: unless-stopped

  # MongoDB Express for database management
  mongo-express:
    image: mongo-express:1.0.0
    container_name: engr_excellence_mongo_express_dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongo
    networks:
      - dev-network
    restart: unless-stopped

  # Redis for caching (optional but useful for development)
  redis:
    image: redis:7.2-alpine
    container_name: engr_excellence_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - dev_redis_data:/data
    networks:
      - dev-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Mailhog for email testing (optional)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: engr_excellence_mailhog_dev
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - dev-network
    restart: unless-stopped

volumes:
  dev_mongodb_data:
    name: engr_excellence_dev_mongodb_data
  dev_redis_data:
    name: engr_excellence_dev_redis_data
  dev_shell_history:
    name: engr_excellence_dev_shell_history
  dev_vscode_extensions:
    name: engr_excellence_dev_vscode_extensions
  dev_pip_cache:
    name: engr_excellence_dev_pip_cache

networks:
  dev-network:
    name: engr_excellence_dev_network
    driver: bridge
